services:
  - type: web
    name: stock-by-chintu
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
